<?php

namespace shopium\mod\telegram\commands;

use function GuzzleHttp\Psr7\parse_query;
use simplehtmldom\HtmlDocument;
use simplehtmldom\HtmlWeb;
use yii\console\Controller;
use Yii;
use shopium\mod\telegram\components\Api;
use yii\console\widgets\Table;

class ParseController extends Controller
{
    public function beforeAction2($action)
    {
        $langManager = Yii::$app->languageManager;
        Yii::$app->language = (isset($langManager->default->code)) ? $langManager->default->code : Yii::$app->language;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionTable(){
        $startime = microtime(true);
        $domain = 'https://amimore.ru';
        $url = $domain . '/category/zajcy';

        $doc = new HtmlWeb();
        $html = $doc->load($domain);

        $data = [];

        foreach ($html->find('#topnav > li span') as $e) {
            /** @var HtmlDocument $e */
            /** @var HtmlDocument $e2 */
            /** @var HtmlDocument $e3 */
            if ($e->innertext == 'Категории') {
                $data = [];
                //level 1
                foreach ($e->find('ul > li') as $cat_key => $e3) {
                    $a = $e3->find('a');
                    $data[$cat_key] = [
                        'name' => $a[0]->innertext,
                        'url' => $a[0]->href
                    ];

                    foreach ($e3->find('ul > li') as $sub_cat_key => $e2) {
                        $a2 = $e2->find('a');
                        $data[$cat_key]['categories'][$sub_cat_key] = [
                            'name' => $a2[0]->innertext,
                            'url' => $a2[0]->href
                        ];


                        $data[$cat_key]['categories'][$sub_cat_key]['products'] = [];
                        $doc = new HtmlWeb();
                        $html = $doc->load($domain . $data[$cat_key]['url']);

                        $find_pager = $html->find('div.pagination a');
                        if ($find_pager) {
                            $pag = last($find_pager);
                            if ($pag) {
                                $pagParams = parse_query($pag->href);
                                //  CMS::dump($pagParams['page']);

                                foreach (range(2, (int)$pagParams['page']) as $pagination) {
                                    $doc2 = new HtmlWeb();
                                    $html2 = $doc2->load($domain . $a2[0]->href . '&page=' . $pagination);

                                    if ($html2) {
                                        foreach ($html2->find('div.pop-mat') as $product) {
                                            $dd = $product->find('h3 a');
                                            $img = $product->find('a img');
                                            $productData=[];

                                            $doc3 = new HtmlWeb();
                                            $html3 = $doc3->load($domain . $dd[0]->href);
                                            foreach ($html3->find('article > p') as $detail) {
                                                $productData['text']=$detail->innertext;
                                            }

                                            $productData['name']=$dd[0]->innertext;
                                            $productData['url']=$dd[0]->href;
                                            $productData['img']=str_replace('/img/mi', '/img/bi', $img[0]->src);

                                            $data[$cat_key]['categories'][$sub_cat_key]['products'][] = $productData;
                                            /*$data[$cat_key]['categories'][$sub_cat_key]['products'][] = [
                                                'name' => $dd[0]->innertext,
                                                'url' => $dd[0]->href,
                                                'img' => str_replace('/img/mi', '/img/bi', $img[0]->src)
                                            ];*/
                                        }
                                    }

                                }
                            }
                        }

                        foreach ($html->find('div.pop-mat') as $product) { // h3 a
                            /** @var HtmlDocument $product */
                            $dd = $product->find('h3 a');
                            $img = $product->find('a img');

                            /*$data[$cat_key]['products'][] = [
                                'name' => $dd[0]->innertext,
                                'url' => $dd[0]->href,
                                'img' => str_replace('/img/mi', '/img/bi', $img[0]->src)
                            ];*/
                        }


                    }
                    if ($cat_key == 0) {
                        break;
                    }
                }
            }

        }
$endtime = microtime(true);
        print_r($data);
        echo $startime - $endtime;
    }

}
